source "https://rubygems.org"

gem 'activesupport'
gem 'algorithms'
gem 'minitest'
gem 'rspec'
gem 'sorbet', :group => :development
gem 'sorbet-runtime'
gem 'tapioca', require: false, :group => [:development, :test]
